require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/question_accesses', type: :request do
  # QuestionAccess. As you add validations to QuestionAccess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      QuestionAccess.create! valid_attributes
      get question_accesses_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      question_access = QuestionAccess.create! valid_attributes
      get question_access_url(question_access)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_question_access_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      question_access = QuestionAccess.create! valid_attributes
      get edit_question_access_url(question_access)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new QuestionAccess' do
        expect do
          post question_accesses_url, params: { question_access: valid_attributes }
        end.to change(QuestionAccess, :count).by(1)
      end

      it 'redirects to the created question_access' do
        post question_accesses_url, params: { question_access: valid_attributes }
        expect(response).to redirect_to(question_access_url(QuestionAccess.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new QuestionAccess' do
        expect do
          post question_accesses_url, params: { question_access: invalid_attributes }
        end.to change(QuestionAccess, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post question_accesses_url, params: { question_access: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested question_access' do
        question_access = QuestionAccess.create! valid_attributes
        patch question_access_url(question_access), params: { question_access: new_attributes }
        question_access.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the question_access' do
        question_access = QuestionAccess.create! valid_attributes
        patch question_access_url(question_access), params: { question_access: new_attributes }
        question_access.reload
        expect(response).to redirect_to(question_access_url(question_access))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        question_access = QuestionAccess.create! valid_attributes
        patch question_access_url(question_access), params: { question_access: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested question_access' do
      question_access = QuestionAccess.create! valid_attributes
      expect do
        delete question_access_url(question_access)
      end.to change(QuestionAccess, :count).by(-1)
    end

    it 'redirects to the question_accesses list' do
      question_access = QuestionAccess.create! valid_attributes
      delete question_access_url(question_access)
      expect(response).to redirect_to(question_accesses_url)
    end
  end
end
